# version: '3.8'

services:
  nest-app:
    build: ./
    # image: rvh2776/nest-demo:latest  #* En vez de crear una imagen con (buil: ./) directamente me bajo la imagen de Docker hub.
    # image: nest-docker:latest  #* En vez de crear una imagen con (buil: ./) directamente me bajo la imagen de Docker hub.
    ports:
      - '3001:3001'
    env_file:
      - .env.development
    depends_on:
      - postgres-db
    networks:
      - red-docker #? Si existe la network para los contenedores la declaro (Si es que quiero que use esta) si no docker crea una automaticamente.


  postgres-db:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    networks:
      - red-docker #? Le digo a la red que se debe conectar postgres-db.

volumes:
  postgres-db:
    external: true #? Le digo a docker que use la red ya existente.

networks:
  red-docker:
    external: true #? Le digo a docker que use la red ya existente.
    # driver: bridge #! Si no existe la red y la quiero declarar uso todo lo anterior, pero en vez de usar la externa uso: driver: true (descomentar esta y comentar: external)



#? Para levantar el proyecto completo en contenedores: la app + postgresDb ejecutamos: docker compose up
#* Para verificar siempre si es la ultima imagen docker la que se va a usar: docker compose --pull y despues: docker compose up