version: '3.8'

services:
  nest-app:
    build: ./
    # image: rvh2776/nest-demo:latest  #* En vez de crear una imagen con (buil: ./) directamtne me bajo la imagen de Docker hub.
    platform: linux/arm64, linux/amd64
    ports:
      - '3001:3001'
    env_file:
      - .env.development
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    platform: linux/arm64, linux/amd64
    volumes:
      - postgres-db:/var/lib/postgresql/data
    env_file:
      - .env.development

volumes:
  postgres-db:


#? Para levantar el proyecto completo en contenedores: la app + postgresDb ejecutamos: docker compose up