version: '3.8'

services:
  nest-app:
    build: ./
    ports:
      - '3001:3001'
    env_file:
      - .env.development
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    env_file:
      - .env.development

volumes:
  postgres-db:


#? Para levantar el proyecto completo en contenedores: la app + postgresDb ejecutamos: docker compose up